### ISSUE TITLE
General error: 1366 Incorrect integer value

### ISSUE THREAD

**Issue by jaaaaaaaaaam** [ThomasBS/domainzter#2]
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'category_id' at row 1 (SQL: insert into `domains`

Getting this error when trying to create a new domain and category at the same time.

**Comment by ThomasBS** [comment]
Hi @jaaaaaaaaaam - I'm unable to reproduce the error. What database are you using? MySQL?

**Comment by jaaaaaaaaaam** [comment]
@ThomasBS Yeah, using 5.6.24
