### ISSUE TITLE
From Front page, error to go to View Single Domain

### ISSUE THREAD

**Issue by kaceo** [ThomasBS/domainzter#6]
in file  resources/views/partials/home.blade.php  line 34
the code generate a url for viewing domain that looks like this
  "domain/{id}/1"  

this is incorrect, and returns an page not found if clicked

the correct url should be something like
  "domain/1"

**Comment by ThomasBS** [comment]
Hmm, I'm unable to reproduce the error. What version are you using of angular? Did you upgrade some dependencies?

**Comment by ThomasBS** [comment]
I'll try to do a clean install and will get back to you

**Comment by ThomasBS** [comment]
Thanks for the notice @kaceo :+1:
